[template]
keys        = [ "role", "master" ]
owner       = "vcap"
mode        = "0644"
src         = "redis.conf.tmpl"
dest        = "/var/vcap/confd/config/redis/redis.conf"
# check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
# reload_cmd  = "/usr/sbin/service nginx reload"
