[template]
keys        = [ "role", "master" ]
owner       = "vcap"
mode        = "0644"
src         = "redis.consul.json.tmpl"
dest        = "/var/vcap/data/consul/redis/redis.json"
# check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd  = "/var/vcap/jobs/consul/bin/consul_ctl reload"
