---
name: redis-solo
director_uuid: 1e62421b-717e-438c-b5e8-b1b64a9bce23
release:
  name: redis
  version: latest
compilation:
  workers: 10
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small
update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  max_errors: 1
networks:
- name: default
  type: dynamic
  cloud_properties:
    security_groups:
    - default
- name: vip_network
  type: vip
  cloud_properties:
    security_groups:
    - default
    - redis-server
resource_pools:
- name: common
  network: default
  size: 1
  stemcell:
    name: bosh-stemcell
    version: latest
  cloud_properties:
    instance_type: m1.small
jobs:
- name: redis
  template: redis
  instances: 1
  resource_pool: common
  networks:
  - name: default
    default:
    - dns
    - gateway
properties:
  redis:
    port: 6379
    password: r3d!s
