networks: (( merge ))

meta:
  environment: ~
  job_templates: (( merge ))
  slaves: (( merge ))
  password: (( merge ))

jobs:
  - name: redis_leader_z1
    templates: (( meta.job_templates ))
    instances: 0
    resource_pool: small_z1
    networks:
      - name: redis1
        static_ips: ~
    persistent_disk: 0
    properties:
      redis:
        password: (( meta.password ))
      network: redis1
  - name: redis_z1
    templates: (( meta.job_templates ))
    instances: (( meta.slaves ))
    resource_pool: small_z1
    networks:
      - name: redis1
        static_ips: ~
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      redis:
        master: (( merge ))
        password: (( meta.password ))
      network: redis1
  - name: acceptance-tests
    templates:
      - name: acceptance-tests
        release: redis
    instances: 1
    lifecycle: errand
    resource_pool: small_z1
    networks:
      - name: redis1
        static_ips: ~
    properties:
      redis:
        master: (( merge ))
        password: (( meta.password ))
