networks: (( merge ))

meta:
  environment: ~
  job_templates: (( merge ))

jobs:
  - name: redis_leader_z1
    templates: (( meta.job_templates ))
    instances: 0
    resource_pool: small_z1
    networks:
      - name: redis1
        static_ips: ~
  - name: redis_z1
    templates: (( meta.job_templates ))
    instances: 0
    resource_pool: small_z1
    networks:
      - name: redis1
        static_ips: ~
    update:
      canaries: 10
    properties:
      redis:
        master: (( merge ))
